export const BLOCKSCOUT_API_URL = {
    eth: "https://eth.blockscout.com/",
    eth_sepolia: "https://eth-sepolia.blockscout.com/",
    op: "https://explorer.optimism.io/",
    op_sepolia: "https://testnet-explorer.optimism.io/",
    rootstock: "https://rootstock.blockscout.com/",
    rootstock_testnet: "https://rootstock-testnet.blockscout.com/",
    etc: "https://etc.blockscout.com/",
    etc_mordor: "https://etc-mordor.blockscout.com/",
    gnosis: "https://gnosis.blockscout.com/",
    gnosis_chiado: "https://gnosis-chiado.blockscout.com/",
    unichain: "https://unichain.blockscout.com/",
    unichain_sepolia: "https://unichain-sepolia.blockscout.com/",
    polygon: "https://polygon.blockscout.com/",
    hashkey: "https://hashkey.blockscout.com/",
    zksync: "https://zksync.blockscout.com/",
    zksync_sepolia: "https://zksync-sepolia.blockscout.com/",
    worldchain: "https://worldchain-mainnet.explorer.alchemy.com/",
    worldchain_sepolia: "https://worldchain-sepolia.explorer.alchemy.com/",
    base: "https://base.blockscout.com/",
    base_sepolia: "https://base-sepolia.blockscout.com/",
    arbitrum: "https://arbitrum.blockscout.com/",
    arbitrum_sepolia: "https://arbitrum-sepolia.blockscout.com/",
    celo: "https://celo.blockscout.com/",
    celo_alfajores: "https://celo-alfajores.blockscout.com/",
    scroll: "https://scroll.blockscout.com/",
    scroll_sepolia: "https://scroll-sepolia.blockscout.com/",
};